### ISSUE TITLE
Include module on download page

### ISSUE THREAD

**Issue by jniggemann** [caddy-dns/inwx#2]
The page https://caddyserver.com/download lets a user select modules and download a customized build. This module is missing.

**Comment by xtrcode** [comment]
+1 would love to see it beeing added!

**Comment by mholt** [comment]
@ihmels You can do this by logging in at the Caddy website and claiming the package :+1:

**Comment by ihmels** [comment]
I have added the module to the Caddy website.

@mholt Thanks for pointing out how to do this. 🙂

**Comment by mholt** [comment]
Yeah no problem! Sorry we don't really highlight that thing a little better. I'll try to make it more apparent for plugin authors in the future.
