### ISSUE TITLE
Add API endpoints to README

### ISSUE THREAD

**Issue by jniggemann** [caddy-dns/inwx#3]
I guess the `endpoint_url` is the INWX API endpoint, isn't it?

Excerpt from https://www.inwx.de/en/help/apidoc/f/ch01.html:

> The addresses of the provided services are:
> * for the test environment https://api.ote.domrobot.com/xmlrpc/
> * for the production environment https://api.domrobot.com/xmlrpc/
 
These endpoints are unlikely to change, perhaps they could even be hardcoded (but that's another subject).  
As this is configurable through `endpoint_url`, I think it's a good idea to link to the INWX API docs in the README.

**Comment by ihmels** [comment]
Yes, it's the JSON-RPC endpoint URL.

I have added a note for the `endpoint_url` and a link to the [libdns/inwx](https://github.com/libdns/inwx) repository.
