### ISSUE TITLE
Docker Build fails

### ISSUE THREAD

**Issue by jb-home** [caddy-dns/inwx#4]
Building a docker image with the v0.3.0 fails with:
`68.52 /go/pkg/mod/github.com/caddyserver/caddy/v2@v2.7.6/listeners.go:477:4: unknown field RequireAddressValidation in struct literal of type quic.Config
68.52 /go/pkg/mod/github.com/caddyserver/caddy/v2@v2.7.6/listeners.go:516:4: unknown field RequireAddressValidation in struct literal of type quic.Config`

Here my docker file:

```
FROM caddy:2-builder AS builder

LABEL org.opencontainers.image.description="caddy + dns inwx"

RUN xcaddy build \
    --with github.com/caddy-dns/inwx

FROM caddy:2

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

Using github.com/caddy-dns/inwx@v0.2.0 works.

**Comment by ihmels** [comment]
I've released a fixed version 0.3.1. I also created a workflow that builds the code with xcaddy as a test.
