### ISSUE TITLE
The confirmation code is invalid

### ISSUE THREAD

**Issue by jniggemann** [caddy-dns/inwx#8]
When caddy tries to get a certificate, I get the following error:
`2024/05/01 12:03:51.964 ERROR   tls.issuance.acme.acme_client   cleaning up solver      {"identifier": "server.tld.com", "challenge_type": "dns-01", "error": "deleting temporary record for name \"_acme-challenge.server.tld.com\" in zone \"tld.com.\": (2200) Authentication error. Reason: (INVALID) The confirmation code is invalid."}
`
Interestingly, a second later the TXT record is correctly present in my INWX DNS.

**Comment by bermeitinger-b** [comment]
Could we reopen this? I guess that there is an underlying problem that results in the wrong error message about the invalid confirmation code.
You should have been able to see the actual error after disabling MFA. I have a similar error when using this: https://github.com/libdns/inwx/issues/10
